# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lensed < Formula
  desc ""
  homepage "https://github.com/mkmik/lokus"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.1/lokus_0.0.1_darwin_arm64.tar.gz"
      sha256 "1e7b32420b5f80712ec06c1ad5d3e4a8ee15ecbf8683454a06bf86d10c41739d"

      def install
        bin.install "lokus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.1/lokus_0.0.1_darwin_amd64.tar.gz"
      sha256 "23ed0feaad96ab9b90cc0d3fa35de76695122c4be8f82f1daf70b46e2ffe25fa"

      def install
        bin.install "lokus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.1/lokus_0.0.1_linux_arm64.tar.gz"
      sha256 "490e1a71283e422a745eea4bb7bcb779d2aadac72f991253b94a5964a85ae07d"

      def install
        bin.install "lokus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.1/lokus_0.0.1_linux_amd64.tar.gz"
      sha256 "5de02e84766868af85fecb307d9213ba7898946cfa6884d2e24d950098dadb07"

      def install
        bin.install "lokus"
      end
    end
  end
end
