# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokus < Formula
  desc ""
  homepage "https://github.com/mkmik/lokus"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.3/lokus_0.0.3_darwin_arm64.tar.gz"
      sha256 "83e5a00d5a5d5b326b9604b037d7a5b7a60904993784b2588d7f92e45f8fdabc"

      def install
        bin.install "lokus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.3/lokus_0.0.3_darwin_amd64.tar.gz"
      sha256 "f2cd629e94028a0ebe857864a0b5c694e204d73ac971346ae969b04722c0b5cf"

      def install
        bin.install "lokus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.3/lokus_0.0.3_linux_arm64.tar.gz"
      sha256 "277e6cb0130869263a84bcb536c0666727cb0115055cf0bfde429134a1530506"

      def install
        bin.install "lokus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.3/lokus_0.0.3_linux_amd64.tar.gz"
      sha256 "0634b58bc834e5feb30088cc3e114a76c70b1be455cd4617f5875812418b6fc7"

      def install
        bin.install "lokus"
      end
    end
  end
end
