# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokus < Formula
  desc ""
  homepage "https://github.com/mkmik/lokus"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.2/lokus_0.0.2_darwin_amd64.tar.gz"
      sha256 "9543c0a818ef571447b40f527bd759d71456800ce5206c9263585dd44a1637f1"

      def install
        bin.install "lokus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.2/lokus_0.0.2_darwin_arm64.tar.gz"
      sha256 "b10aeb0bb03ebaaaa49ebd902fa3b1549700657b906f922ccae8337a5fd4548f"

      def install
        bin.install "lokus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.2/lokus_0.0.2_linux_arm64.tar.gz"
      sha256 "3351bb118bb1d77dc3d245f187bfafaf9f48ccb7cdf4a922f87d6f13dfb7ec2c"

      def install
        bin.install "lokus"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/lokus/releases/download/v0.0.2/lokus_0.0.2_linux_amd64.tar.gz"
      sha256 "6f590f869b9c97d0e78d13b3de93ce9c26ceec0fc5e811f62de02899e7b5e895"

      def install
        bin.install "lokus"
      end
    end
  end
end
